name: Build & Push
on:
  pull_request:
    branches:
      - main
      - rc*/*
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10
      - "v[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching v*, i.e. v1.0-rc1, v20.15.10-rc5
env:
  registry: docker.io
  repository: finschia/finschia-simapp
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: login to the registry
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ${{env.registry}}
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: extract metadata for docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{env.registry}}/${{env.repository}}
          tags: |
            type=semver,pattern={{version}}
      - name: docker build
        uses: docker/build-push-action@v4
        with:
          push: ${{github.event_name != 'pull_request'}}
          build-args: ARCH=x86_64
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
          platforms: linux/amd64
