name: Protobuf
# Protobuf runs buf (https://buf.build/) lint and check-breakage
# This workflow is only run when a .proto file has been changed
on:
  pull_request:
    paths:
      - "**.proto"
jobs:
  lint:
    name: proto-lint(clang-format)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.15
        with:
          source: '.'
          exclude: './third_party'
          extensions: 'proto'
          clangFormatVersion: 12
          inplace: True
  swagger:
    name: check generated swagger files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4.0.0
        with:
          go-version: 1.18
      - uses: ./.github/actions/generate-swagger
      - name: diff
        run: git diff

# TODO ebony: release comment after merging initial proto files to v2 branch
#  breakage:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: check-breakage
#        run: make proto-check-breaking
