name: Release Sims
# Release Sims workflow runs long-lived (multi-seed & large block size) simulations
# This workflow only runs on a pull request added `release` label
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
    branches:
      - main
      - rc*/*
      - release/*

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main' && contains(github.event.pull_request.labels.*.name, 'release')"

  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-sims') && contains(github.event.pull_request.labels.*.name, 'release')"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - run: |
          make build

  install-runsim:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - name: install runsim
        run: |
          export GO111MODULE="on" && go install github.com/cosmos/tools/cmd/runsim@v1.0.0
      - uses: actions/cache@v4.0.1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary

  test-sim-multi-seed-long-part1:
    runs-on: ubuntu-latest
    needs: [build, install-runsim]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - uses: actions/cache@v4.0.1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
      - name: test-sim-multi-seed-long-part1
        env:
          USE_PREFETCH: NO
          USE_PRELOAD: 1,4
          SAVE_BRANCH_LAUNCH_DEPTH: 1
        run: |
          make test-sim-multi-seed-long-part1

  test-sim-multi-seed-long-part2:
    runs-on: ubuntu-latest
    needs: [build, install-runsim, test-sim-multi-seed-long-part1]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - uses: actions/cache@v4.0.1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
      - name: test-sim-multi-seed-long-part2
        env:
          USE_PREFETCH: NO
          USE_PRELOAD: 1,4
          SAVE_BRANCH_LAUNCH_DEPTH: 1
        run: |
          make test-sim-multi-seed-long-part2

  test-sim-multi-seed-long-part3:
    runs-on: ubuntu-latest
    needs: [build, install-runsim, test-sim-multi-seed-long-part2]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - uses: actions/cache@v4.0.1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
      - name: test-sim-multi-seed-long-part3
        env:
          USE_PREFETCH: NO
          USE_PRELOAD: 1,4
          SAVE_BRANCH_LAUNCH_DEPTH: 1
        run: |
          make test-sim-multi-seed-long-part3
